### ISSUE TITLE
“routing-api” on controller VM kept crashing because it can't connect locket service

### ISSUE THREAD

**Issue by Nilesh7756** [cloudfoundry/routing-release#136]
## Issue

We see that the “routing-api” on controller VM kept crashing because it can't connect locket service.
Hence router VM's 'gorouter' service gets failed with below Error:

gorouter.stdout.log from router VM
 
{"log_level":6,"timestamp":1550040075.4952705,"message":"routing-api-connection-failed","source":"vcap.gorouter","data":{"error":"Get http://routing-api.service.cf.internal:3000/routing/v1/routes: dial tcp 192.168.2.19:3000: connect: connection refused"}}

## Context
We have PAS + NSX-T setup:

PAS build 2.4.1-build.133

We see that the “routing-api” on controller VM kept crashing, hence router VM's 'gorouter' service gets failed.

routing-api.stdout.log 

"timestamp":"1549957256.365380049","source":"routing-api","message":"routing-api.api-server.uaa-client.fetch-key-starting","log_level":1,"data":{"endpoint":"https://uaa.service.cf.internal:8443/token_key","session":"1.3"}}
{"timestamp":"1549957256.371240377","source":"routing-api","message":"routing-api.api-server.uaa-client.fetch-key-successful","log_level":1,"data":{"session":"1.3"}}
{"timestamp":"1549957257.372670412","source":"routing-api","message":"routing-api.failed-to-create-locket-client","log_level":3,"data":{"error":"context deadline exceeded","trace":"goroutine 1 [running]:\ncode.cloudfoundry.org/lager.(*logger).Fatal(0xc0001ebda0, 0xafed3a, 0x1e, 0xb9e980, 0x10bf060, 0x0, 0x0, 0x0)\n\t/var/vcap/data/compile/routing-api/src/code.cloudfoundry.org/lager/logger.go:132 +0xcd\nmain.main()\n\t/var/vcap/data/compile/routing-api/src/code.cloudfoundry.org/routing-api/cmd/routing-api/main.go:145 +0x18e0\n"}}
uaa.service.cf.internal has address 192.168.2.18
{"timestamp":"1549957267.460693598","source":"routing-api","message":"routing-api.database","log_level":1,"data":{"host":"mysql.service.cf.internal","port":3306}}

We think the error must be from grpc.Dial(config.LocketAddress, ...)

But there was no detailed log to explain why the grpc connection failed. So we cannot isolate the exact problem.

## Expected result

“routing-api” service on controller VM should be alway Up and RUNNING. It should get connect with locket service.

## Current result

[describe what you you currently experience from this process, and thereby explain the bug]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` Output Results

[if relevant, include a screenshot]

**Comment by shubhaat** [comment]
@Nilesh7756 since you are using PAS are you able to raise a support ticket with Pivotal for this?

**Comment by ameowlia** [comment]
Hi all, 

We are closing this issue due to inactivity. We are assuming this has been fixed via a support ticket. If this is still an issue, we encourage you to open a support ticket.

Thanks, 
@ameowlia and @bruce-ricard, CF Networking Program Members
