### ISSUE TITLE
Unable to resolve *.nats.service.cf.internal on a broker machine in different deployment

### ISSUE THREAD

**Issue by cagric0** [cloudfoundry/routing-release#307]
## Is this a security vulnerability?

No

## Issue

After updating the Ubuntu stemcell version to the Jammy on our setup, Our route_registrar couldn't resolve nats.service.cf.internal.
  

## Affected Versions

cf-deployment -> v20.3.0
routing release -> v0.248.0
## Context

 
 
Initially we were using nats with Ubuntu stemcell version Bionic 1.84 then we decided to replace nats with nats-tls. At that time we had a similar problem with resolving `nats.service.cf.internal`. Then we used `bosh-dns-aliases` addon for solving the problem. But currently, we upgraded our Ubuntu stemcell version to Jammy, and it seems that bosh-dns-aliases is not working. There is no log for the addon. 
   
## Steps to Reproduce

You can just create a deployment using the manifest shared below. I didn't put tls cert, tls key and hazelcast license key since we don't want them to be publicly available. If you want to reproduce the issue, please add me to your community slack channel and I can share them in need.
   
bosh -d hz-mc deploy manifest.yaml

## Current result

Output of the deploy command:
`L Error: 'management-center/651776a5-97b6-4482-b861-7bfb99131ac7 (0)' is not running after update. Review logs for failed jobs: route_registrar
`

Error log on the route_registrar:
`goroutine 1 [running]: code.cloudfoundry.org/lager.(*logger).Fatal(0xc0000ae360, {0x74c1e3, 0x12}, {0x7d5720?, 0xc000196140}, {0x0, 0x0, 0x0?}) /var/vcap/data/compile/route_registrar/src/code.cloudfoundry.org/vendor/code.cloudfoundry.org/lager/logger.go:162 +0x5dc
main.main()
/var/vcap/data/compile/route_registrar/src/code.cloudfoundry.org/route-registrar/main.go:138 +0x111a
panic: dial tcp: lookup nats.service.cf.internal on 10.0.0.2:53: no such host`

`{"timestamp":"2023-01-11T11:00:53.289166840Z","level":"error","source":"Route Registrar","message":"Route Registrar.nats-connection-failed","data":{"error":"dial tcp: lookup nats.service.cf.internal on 10.0.0.2:53: no such host","nats-hosts":["nats.service.cf.internal:4224"]}}
`
## Additional Context

manifest.yaml:
````
name: hz-mc
releases:
  - name: hazelcast-boshrelease
    version: 5.2.1
  - name: routing
    version: 0.248.0
  - name:  bosh-dns-aliases
    version: 0.0.4
  - name: bpm  
    version: 1.1.19
stemcells:
  - alias: only-stemcell
    os: "ubuntu-jammy"
    version: "1.49"
instance_groups:
  - name: management-center
    instances: 1
    jobs:
      - name: management-center
        release: hazelcast-boshrelease
        properties:
          config_json:
            hazelcast:
              license-key:  <hazelcast-license-key>
            hazelcast-pcf:
              debug: true
              instanceCount: 1
              management-center:
                appName: mancenter
                enabled: true
      - name: route_registrar
        release: routing
        consumes:
          nats-tls:
            deployment: cf
            from: nats-tls
        properties:
          nats:
            machines:
              - nats.service.cf.internal
            password: nkhd2oa69oab0bgwnwzz
            port: 4224
            tls:
              enabled: true
              client_cert: |
                -----BEGIN CERTIFICATE-----
                <cert>
                -----END CERTIFICATE-----
              client_key: |
                -----BEGIN RSA PRIVATE KEY-----
                <key>
                -----END RSA PRIVATE KEY-----
            user: nats
          route_registrar:
            routes:
              - name: mancenter
                port: 8080
                tags: {}
                uris:
                  - mancenter.apps.demo.cf.hazelcast.com
                route_service_url: ""
                registration_interval: 20s
    vm_type: default
    stemcell: only-stemcell
    persistent_disk_type: 1GB
    azs:
      - z1
      - z2
    networks:
      - name: default
  - name: hazelcast
    instances: 1
    jobs:
      - name: hazelcast
        release: hazelcast-boshrelease
        properties:
          config_json:
            hazelcast:
              license-key: <hazelcast-license-key>
            hazelcast-pcf:
              debug: true
              instanceCount: 1
              management-center:
                appName: mancenter
                enabled: true
          network: default
    vm_type: default
    stemcell: only-stemcell
    persistent_disk_type: 1GB
    azs:
      - z1
      - z2
    networks:
      - name: default
update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-240000
  max_in_flight: 1
  serial: false

addons:
- name: bpm
  include:
    stemcell:
    - os: ubuntu-xenial
    - os: ubuntu-bionic
    - os: ubuntu-jammy
  jobs:
  - name: bpm
    release: bpm
- name: bosh-dns-aliases
  include:
    stemcell:
    - os: ubuntu-jammy  
  jobs:
  - name: bosh-dns-aliases
    release: bosh-dns-aliases
    properties:
      aliases:
      - domain: nats.service.cf.internal
        targets:
        - query: '*'
          instance_group: nats
          deployment: cf
          network: default
          domain: bosh
      - domain: _.nats.service.cf.internal
        targets:
        - query: '_'
          instance_group: nats
          deployment: cf
          network: default
          domain: bosh

**Comment by reneighbor** [comment]
Hi @cagric0,

Thanks for writing, I see that route registrat on the management-center VM is not able to reach nats-tls.

If you're still experiencing this error, do you mind sending me the `bosh -d cf instances` output at the time of the hazelcast deployment to confim that nats is up?

If nats-tls is indeed running, we should troubleshoot  the nats-tls information to confirm that it bosh-dns able to locate the target target.

Do you mind logging onto the management-center VM and sending me the output of `/etc/hosts`? For comparison, can you also log onto a diego-cell and send me the `/etc/hosts`.

Lastly, can you send your cf manifest so I can check that the nats-tls job is defined in a way that the `hz-mc` bosh dns will find it.

Thanks,
Renee

**Comment by cagric0** [comment]
Thanks for the response, Renee. Here are the outputs you wanted.

The output of `bosh -d cf instances`:
```
Using environment 'https://10.0.0.6:25555' as client 'admin'

Task 191521. Done

Deployment 'cf'

Instance                                                     Process State  AZ  IPs         Deployment  
api/0a9785c5-869a-4b74-bb03-8957b809659c                     running        z1  10.0.16.8   cf  
api/e63c855e-04f5-48c1-8ada-6c4eec9eedf1                     running        z2  10.0.32.7   cf  
cc-worker/aaa36083-8efa-4c7a-9ee6-9f1fe06c4a9d               running        z2  10.0.32.8   cf  
cc-worker/d19c46ab-87a9-4ad2-bd55-64762f19f4b8               running        z1  10.0.16.9   cf  
credhub/64d53c28-7ead-4758-ba18-9428ea20f8c4                 running        z2  10.0.32.15  cf  
credhub/e4facf18-0e3a-4655-87c6-968627342078                 running        z1  10.0.16.19  cf  
database/e792ffbe-2f18-4421-b59a-b3add9b445b1                running        z1  10.0.16.5   cf  
diego-api/2c431d4f-5ee1-45e4-bf71-eab6f22c2b62               running        z1  10.0.16.6   cf  
diego-api/d70e6c61-e4fa-437c-98f4-c9a8207714a2               running        z2  10.0.32.5   cf  
diego-cell/b84512f4-5903-4b8c-ab4f-82ea42cee98b              running        z1  10.0.16.17  cf  
diego-cell/c9297aaf-10b2-46b6-9a2d-928eac558559              running        z2  10.0.32.13  cf  
diego-cell/dd8df783-99dc-423c-9da3-120b91237686              running        z1  10.0.16.16  cf  
doppler/4c054254-5080-4396-bb81-16064310d165                 running        z2  10.0.32.12  cf  
doppler/6bef8962-da44-4e7f-8a51-a945044a5171                 running        z1  10.0.16.15  cf  
doppler/e02795de-8511-498b-a6b5-760e38891e42                 running        z1  10.0.16.14  cf  
log-api/90d01179-eef9-4283-a0bd-e8d56d533853                 running        z2  10.0.32.14  cf  
log-api/a1e44106-1427-43e5-a13b-3e1b14635e5c                 running        z1  10.0.16.18  cf  
log-cache/ca1890ec-9ef6-4352-aa59-ab867001fa8a               running        z1  10.0.16.13  cf  
nats/716840c9-99b0-48e4-85e7-2117cba8f97b                    running        z2  10.0.32.4   cf  
nats/e66860cf-bf79-4cad-9a37-77ee0c4b1f9f                    running        z1  10.0.16.4   cf  
rotate-cc-database-key/43a54912-4d57-4367-92a1-a26345a0ea5e  -              z1  -           cf  
router/539ca9b0-3afa-474a-a1bb-86d9b1f5729a                  running        z1  10.0.16.11  cf  
router/a1f054e5-3bec-4969-b851-a80d81313379                  running        z2  10.0.32.10  cf  
scheduler/449ce60e-d2d3-467e-8796-ab993fea0597               running        z1  10.0.16.10  cf  
scheduler/9cef7b03-4fdb-4395-a61e-382ac3214e25               running        z2  10.0.32.9   cf  
smoke-tests/ff789143-9d2f-44ed-89b2-42e30d989485             -              z1  -           cf  
tcp-router/3593b52c-e3c1-4711-af71-af865990d54f              running        z1  10.0.16.12  cf  
tcp-router/bea74905-de5a-4e0a-8a94-c8703e24d3cd              running        z2  10.0.32.11  cf  
uaa/6a2608ed-c3be-463c-bc9d-880787a2ce77                     running        z2  10.0.32.6   cf  
uaa/ffb26b5a-78f8-4f80-abf8-0510959f1356                     running        z1  10.0.16.7   cf  

30 instances

Succeeded
```

The output of `management-center vm /etc/hosts`:
```
127.0.0.1 18295ef4-17e4-43a8-91a7-2c8657cce889 localhost

# The following lines are desirable for IPv6 capable hosts
::1 18295ef4-17e4-43a8-91a7-2c8657cce889 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
10.0.32.7 e63c855e-04f5-48c1-8ada-6c4eec9eedf1.api.default.cf.bosh
10.0.32.4 716840c9-99b0-48e4-85e7-2117cba8f97b.nats.default.cf.bosh
10.0.16.19 e4facf18-0e3a-4655-87c6-968627342078.credhub.default.cf.bosh
10.0.16.26 8216fe4d-a092-44bf-b94b-90fe7f9b3deb.management-center.default.cc.bosh
10.0.16.25 f1f8d4e0-6752-42e4-ae7c-c50623c40f4b.hazelcast.default.bb.bosh
10.0.16.27 e17bdfbc-f8af-4314-bd8c-43faa96196b0.hazelcast.default.cc.bosh
10.0.16.20 06e5384a-569c-4d4d-beb5-f1ff7ec1aad2.management-center.default.zz.bosh
10.0.16.21 0d67956a-4ded-4140-b62a-b96a1b400fa9.hazelcast.default.zz.bosh
10.0.16.22 93264b43-fbfc-48ed-b825-8ebe31162c21.management-center.default.xx.bosh
10.0.16.4 e66860cf-bf79-4cad-9a37-77ee0c4b1f9f.nats.default.cf.bosh
10.0.16.5 e792ffbe-2f18-4421-b59a-b3add9b445b1.database.default.cf.bosh
10.0.16.6 2c431d4f-5ee1-45e4-bf71-eab6f22c2b62.diego-api.default.cf.bosh
10.0.32.5 d70e6c61-e4fa-437c-98f4-c9a8207714a2.diego-api.default.cf.bosh
10.0.16.7 ffb26b5a-78f8-4f80-abf8-0510959f1356.uaa.default.cf.bosh
10.0.32.6 6a2608ed-c3be-463c-bc9d-880787a2ce77.uaa.default.cf.bosh
10.0.16.8 0a9785c5-869a-4b74-bb03-8957b809659c.api.default.cf.bosh
10.0.16.9 d19c46ab-87a9-4ad2-bd55-64762f19f4b8.cc-worker.default.cf.bosh
10.0.32.8 aaa36083-8efa-4c7a-9ee6-9f1fe06c4a9d.cc-worker.default.cf.bosh
10.0.16.10 449ce60e-d2d3-467e-8796-ab993fea0597.scheduler.default.cf.bosh
10.0.32.9 9cef7b03-4fdb-4395-a61e-382ac3214e25.scheduler.default.cf.bosh
10.0.16.11 539ca9b0-3afa-474a-a1bb-86d9b1f5729a.router.default.cf.bosh
10.0.32.10 a1f054e5-3bec-4969-b851-a80d81313379.router.default.cf.bosh
10.0.16.12 3593b52c-e3c1-4711-af71-af865990d54f.tcp-router.default.cf.bosh
10.0.32.11 bea74905-de5a-4e0a-8a94-c8703e24d3cd.tcp-router.default.cf.bosh
10.0.16.13 ca1890ec-9ef6-4352-aa59-ab867001fa8a.log-cache.default.cf.bosh
10.0.16.14 e02795de-8511-498b-a6b5-760e38891e42.doppler.default.cf.bosh
10.0.16.15 6bef8962-da44-4e7f-8a51-a945044a5171.doppler.default.cf.bosh
10.0.32.12 4c054254-5080-4396-bb81-16064310d165.doppler.default.cf.bosh
10.0.16.16 dd8df783-99dc-423c-9da3-120b91237686.diego-cell.default.cf.bosh
10.0.16.17 b84512f4-5903-4b8c-ab4f-82ea42cee98b.diego-cell.default.cf.bosh
10.0.32.13 c9297aaf-10b2-46b6-9a2d-928eac558559.diego-cell.default.cf.bosh
10.0.16.18 a1e44106-1427-43e5-a13b-3e1b14635e5c.log-api.default.cf.bosh
10.0.32.14 90d01179-eef9-4283-a0bd-e8d56d533853.log-api.default.cf.bosh
10.0.32.15 64d53c28-7ead-4758-ba18-9428ea20f8c4.credhub.default.cf.bosh
10.0.16.23 d40e8838-e6da-4eab-a39c-197ab7239489.hazelcast.default.xx.bosh
10.0.16.24 651776a5-97b6-4482-b861-7bfb99131ac7.management-center.default.bb.bosh
```

The output of `diego-cell vm /etc/hosts`:
```
127.0.0.1 bf52218a-0c4b-4a4a-a506-b8d85f3827b5 localhost

# The following lines are desirable for IPv6 capable hosts
::1 bf52218a-0c4b-4a4a-a506-b8d85f3827b5 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
10.0.32.7 e63c855e-04f5-48c1-8ada-6c4eec9eedf1.api.default.cf.bosh
10.0.32.4 716840c9-99b0-48e4-85e7-2117cba8f97b.nats.default.cf.bosh
10.0.16.19 e4facf18-0e3a-4655-87c6-968627342078.credhub.default.cf.bosh
10.0.16.26 8216fe4d-a092-44bf-b94b-90fe7f9b3deb.management-center.default.cc.bosh
10.0.16.25 f1f8d4e0-6752-42e4-ae7c-c50623c40f4b.hazelcast.default.bb.bosh
10.0.16.27 e17bdfbc-f8af-4314-bd8c-43faa96196b0.hazelcast.default.cc.bosh
10.0.16.20 06e5384a-569c-4d4d-beb5-f1ff7ec1aad2.management-center.default.zz.bosh
10.0.16.21 0d67956a-4ded-4140-b62a-b96a1b400fa9.hazelcast.default.zz.bosh
10.0.16.22 93264b43-fbfc-48ed-b825-8ebe31162c21.management-center.default.xx.bosh
10.0.16.4 e66860cf-bf79-4cad-9a37-77ee0c4b1f9f.nats.default.cf.bosh
10.0.16.5 e792ffbe-2f18-4421-b59a-b3add9b445b1.database.default.cf.bosh
10.0.16.6 2c431d4f-5ee1-45e4-bf71-eab6f22c2b62.diego-api.default.cf.bosh
10.0.32.5 d70e6c61-e4fa-437c-98f4-c9a8207714a2.diego-api.default.cf.bosh
10.0.16.7 ffb26b5a-78f8-4f80-abf8-0510959f1356.uaa.default.cf.bosh
10.0.32.6 6a2608ed-c3be-463c-bc9d-880787a2ce77.uaa.default.cf.bosh
10.0.16.8 0a9785c5-869a-4b74-bb03-8957b809659c.api.default.cf.bosh
10.0.16.9 d19c46ab-87a9-4ad2-bd55-64762f19f4b8.cc-worker.default.cf.bosh
10.0.32.8 aaa36083-8efa-4c7a-9ee6-9f1fe06c4a9d.cc-worker.default.cf.bosh
10.0.16.10 449ce60e-d2d3-467e-8796-ab993fea0597.scheduler.default.cf.bosh
10.0.32.9 9cef7b03-4fdb-4395-a61e-382ac3214e25.scheduler.default.cf.bosh
10.0.16.11 539ca9b0-3afa-474a-a1bb-86d9b1f5729a.router.default.cf.bosh
10.0.32.10 a1f054e5-3bec-4969-b851-a80d81313379.router.default.cf.bosh
10.0.16.12 3593b52c-e3c1-4711-af71-af865990d54f.tcp-router.default.cf.bosh
10.0.32.11 bea74905-de5a-4e0a-8a94-c8703e24d3cd.tcp-router.default.cf.bosh
10.0.16.13 ca1890ec-9ef6-4352-aa59-ab867001fa8a.log-cache.default.cf.bosh
10.0.16.14 e02795de-8511-498b-a6b5-760e38891e42.doppler.default.cf.bosh
10.0.16.15 6bef8962-da44-4e7f-8a51-a945044a5171.doppler.default.cf.bosh
10.0.32.12 4c054254-5080-4396-bb81-16064310d165.doppler.default.cf.bosh
10.0.16.16 dd8df783-99dc-423c-9da3-120b91237686.diego-cell.default.cf.bosh
10.0.16.17 b84512f4-5903-4b8c-ab4f-82ea42cee98b.diego-cell.default.cf.bosh
10.0.32.13 c9297aaf-10b2-46b6-9a2d-928eac558559.diego-cell.default.cf.bosh
10.0.16.18 a1e44106-1427-43e5-a13b-3e1b14635e5c.log-api.default.cf.bosh
10.0.32.14 90d01179-eef9-4283-a0bd-e8d56d533853.log-api.default.cf.bosh
10.0.32.15 64d53c28-7ead-4758-ba18-9428ea20f8c4.credhub.default.cf.bosh
10.0.16.23 d40e8838-e6da-4eab-a39c-197ab7239489.hazelcast.default.xx.bosh
10.0.16.24 651776a5-97b6-4482-b861-7bfb99131ac7.management-center.default.bb.bosh
```

The manifest file for `hz-mc` deployment is under the `Additional Context` in the issue description.

https://github.com/cloudfoundry/routing-release/issues/307#issue-1534721889

**Comment by hasancelik** [comment]
Hi @reneighbor,

Do you happen to have any updates on this issue?

**Comment by reneighbor** [comment]
Hello @cagric0 @hasancelik ,

I'm sorry this issue fell by the wayside. It does look like the `management-center` 's /etc/hosts file has the right information for locating nats.

First off, is this issue still occurring? If it is, out of curiosity, if you do `monit restart route_registrar` from the management center and let me know if route registrar is able to find nats? Because the /etc/hosts has the right address for nats, I'm wondering if it's a timing issue with the nats instances not being available when the service instance is registering.

Also, to see whether the issue is with BOSH DNS, can you run `dig nats.service.cf.internal` and share the output? Can you also run the same command from a diego cell?

Thank you,
Renee

**Comment by jrussett** [comment]
Closing due to inactivity. Please open this issue again if the problem still persists and we can help take a look at it.
